### ISSUE TITLE
Roles with `moodle/course:view` are not enrolled when added as attendee

### ISSUE THREAD

**Issue by djarran** [catalyst/moodle-mod_facetoface#227]
**Description:** Users are enrolled into the course when added as attendees. However, this is not working for admin and manager roles as this call to `has_capability` returns true, and so we don't enter the conditional

https://github.com/catalyst/moodle-mod_facetoface/blob/b4887643901059c30acf6630706b9526a6215c05/editattendees.php#L94-L109

**Comment by golenkovm** [comment]
Fixed in https://github.com/catalyst/moodle-mod_facetoface/pull/228

**Comment by djarran** [comment]
Reopening this issue. We've previously addressed manually adding attendees to a session, but this is still occurring when users themselves (those with the system `moodle/course:view` capability) signup for a session.

**Comment by golenkovm** [comment]
Implemented in https://github.com/catalyst/moodle-mod_facetoface/pull/237
